---
- name: Add cron.d file(s)
  tags:
    - configure
  when: >
    cron is defined
    and
    cron is iterable
    and
    item.state | default("present") == "present"
  ansible.builtin.template:
    src: cron.j2
    dest: /etc/cron.d/{{ item.file }}
    mode: "0644"
  with_items: "{{ cron }}"

- name: Delete cron.d file(s)
  tags:
    - configure
  when: >
    cron is defined
    and
    cron is iterable
    and
    item.state | default("present") == "absent"
  ansible.builtin.file:
    path: /etc/cron.d/{{ item.file }}
    state: absent
  with_items: "{{ cron }}"

# - name: Creates a cron file under /etc/cron.d
#   ansible.builtin.cron:
#     name: yum autoupdate
#     weekday: "2"
#     minute: "0"
#     hour: "12"
#     user: root
#     job: "YUMINTERACTIVE=0 /usr/sbin/yum-autoupdate"
#     cron_file: ansible_yum-autoupdate

# - name: Removes a cron file from under /etc/cron.d
#   ansible.builtin.cron:
#     name: "yum autoupdate"
#     cron_file: ansible_yum-autoupdate
#     state: absent
